<?php
/**
 * @category    DGT
 * @package     DGT_Widget
 * Copyright (C) 2014-2015 dragontheme.com. All Rights Reserved.
 * @license     GNU General Public License version 2 or later
 * @author      dragontheme.com
 * @email       support@dragontheme.com
 */
?>
<?php
$theme = $this->helper('dgtyaris');
$helpImg = $this->helper('dgtyaris/image');
$imgWidth = $theme->getCfg('category/image_width') ? $theme->getCfg('category/image_width') : 295;
$imgHeight = $theme->getCfg('category/image_height') ? $theme->getCfg('category/image_height') : 295;
if ($theme->getCfg('category/aspect_ratio')) {
    $imgHeight = 0;
}
$cfaltimage = $theme->getCfg('category/alt_image');
$hoveraltClass = ($cfaltimage == 1) ? 'front-img' : '';
$_helper = $this->helper('catalog/output');
/* @var $this DGT_Widget_Block_Widget_Collection */
$_productCollection = $this->getData('collection');
$count = $_productCollection ? $_productCollection->count() : 0;
$countdown = $this->getData('countdown');
$carousel = $this->getData('carousel');
$row = $this->getData('row');
$column_no = $this->getData('columnslider');
$class_no = 12 / $column_no;
$column = $carousel == 1 && $row == 1 ? $count : ($carousel == 1 && $row > 1 ? $row : $this->getData('column'));
if($carousel == 0){
    $column = $column_no;
}
/* @var $helper Mage_Catalog_Helper_Image */
$helper = Mage::helper('catalog/image');
?>

<?php if (!$count): ?>
    <p class="note-msg">
        <?php echo $this->__('There are no products matching the selection.') ?>
    </p>
<?php else: ?>
    <?php if($carousel == 0) { ?>
        <div class="category-products product-boxed">
        <ul class="products-grid row">
    <?php } ?>
    <?php $i = 0;
    foreach ($_productCollection as $_product): ?>
        <?php if ($carousel == 1 && $row > 1 && $i == 0): ?>
            <div class="owl-carousel">
        <?php endif ?>
        <?php if($carousel == 1) { ?>
        <?php if ($i % $column == 0 || ($row > 1 && $i % $row == 0)): ?>
        <div class="category-products product-boxed">
        <ul class="products-grid <?php echo $carousel && $row == 1 ? ' owl-carousel' : '' ?>">
        <?php endif ?>
        <?php } ?>

        <?php $i++ ?>
        <li class="item product-default product-item <?php echo ($carousel == 0) ? 'col-md-' . $class_no . ' ' . 'col-sm-6' . ' product-no-slider    ' : ''; ?>">
            <div class="item-inner">
                <div class="product-content products-list">
                    <div class="product-hover">
                        <a href="<?php echo $_product->getProductUrl() ?>"
                           title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"
                           class="product-image">
                            <?php echo $this->helper('dgtyaris')->getLabel($_product); ?>
                            <span class="front margin-image">
                            <?php if ($carousel == 1): ?>
                                <img class="lazyOwl"
                                     data-srcX2="<?php echo $helper->init($_product, 'small_image')->resize($imgWidth * 2, $imgHeight * 2) ?>"
                                     data-src="<?php echo $helper->init($_product, 'small_image')->resize($imgWidth, $imgHeight) ?>"
                                     src="<?php echo $this->getSkinUrl('images/loader.gif') ?>"
                                     width="<?php echo $imgWidth; ?>" height="<?php echo $imgHeight; ?>"
                                     alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"/>
                            <?php else: ?>
                                <img src="<?php echo $helper->init($_product, 'small_image')->resize($imgWidth, $imgHeight) ?>"
                                     width="<?php echo $imgWidth; ?>" height="<?php echo $imgHeight; ?>"
                                     alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"/>
                            <?php endif ?>
                            </span>
                            <?php if ($theme->getCfg('category/alt_image')): ?>
                                <span class="product-img-additional back margin-image">
										 <?php echo $theme->getAltImgHtml($_product, $imgWidth, $imgHeight); ?>
									</span>
                            <?php endif; ?>
                        </a>
                    </div>
                    <div class="dgt-actions clearfix">
                        <ul class="add-to-links pull-left">
                            <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                <li class="wishlist">
                                    <a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>"
                                       title="<?php echo $this->__('Add To Wishlist') ?>" class="link-wishlist dgt-tooltip"><i
                                            class="fa fa fa-heart-o"></i><?php //echo $this->__('Wishlist') ?></a>
                                </li>
                            <?php endif; ?>
                            <?php if ($_compareUrl = $this->getAddToCompareUrl($_product)): ?>
                                <li class="compare">
                                    <a href="<?php echo $_compareUrl ?>" title="<?php echo $this->__('Add To Compare') ?>"
                                       class="link-compare dgt-tooltip"><i
                                            class="fa fa-compress"></i><?php //echo $this->__('Compare') ?></a>
                                </li>
                            <?php endif; ?>
                            <li class="main-quickview hidden-xs">
                                <a href="#" class="button link-quickview btn-quickview dgt-tooltip show-quickview" data-id="<?php echo $_product->getId(); ?>"><i class="fa fa-search"></i></a>
                            </li>
                            <a class="product-quickview"
                               href="<?php echo $this->getUrl('ajaxcart/index/options/product_id/' . $_product->getId()); ?>"
                               data-id='quickview-<?php echo $_product->getId() ?>'
                               style='display:none'><?php echo $this->__('Quick view') ?></a>
                        </ul>
                    </div>
                </div>

                <div class="top-actions-inner clearfix">
                    <h3 class="product-name">
                        <a href="<?php echo $_product->getProductUrl() ?>"
                           title="<?php echo $this->stripTags($_product->getName(), null, true) ?>">
                            <?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                        </a>
                    </h3>
                    <?php echo $this->getPriceHtml($_product, true) ?>
                    <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                </div>
                <div class="addtocart clearfix al-center">
                    <?php if ($_product->isSaleable()): ?>
                        <?php if (!($_product->getTypeInstance(true)->hasRequiredOptions($_product) || $_product->isGrouped()) || $oType == true) { ?>
                            <button type="button" title="<?php echo $this->__('Add To Cart') ?>"
                                    data-placement="top"
                                    class="button btn-cart dgt-tooltip <?php if ($oType == true) echo 'option-file'; ?>"
                                    onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')">
                                        <span>
                                             <span><i
                                                     class="fa fa-shopping-cart"></i><?php echo $this->__('Add To Cart') ?></span>
                                        </span>
                            </button>
                        <?php } else { ?>
                            <?php if (Mage::getStoreConfig('ajaxcart/ajaxcart_config/enable_ajaxcart')) : ?>
                                <a style="display: none;"
                                   href='<?php echo $this->getUrl('ajaxcart/index/options', array('product_id' => $_product->getId())); ?>'
                                   class='options-cart'
                                   data-id='options-cart-<?php echo $_product->getId() ?>'><?php echo $this->__('Option cart') ?></a>
                            <?php endif; ?>

                            <button type="button" title="<?php echo $this->__('Add To Cart') ?>"
                                    data-placement="top" class="button btn-cart show-options dgt-tooltip"
                                    data-id="<?php echo $_product->getId(); ?>"
                                <?php if (!Mage::getStoreConfig('ajaxcart/ajaxcart_config/enable_ajaxcart')) { ?>
                                    onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"
                                <?php } ?> data-submit='<?php echo $this->getAddToCartUrl($_product) ?>'>
                                    <span>
                                       <span><i
                                               class="fa fa-shopping-cart"></i><?php echo $this->__('Add To Cart') ?></span>
                                    </span>
                            </button>

                        <?php } ?>
                    <?php else: ?>
                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span>
                        </p>
                    <?php endif; ?>
                </div>
            </div>
            <div class="product-date" data-date="<?php echo Mage::helper('dgtwidget')->getDate($_product) ?>"></div>
        </li>
        <?php if($carousel == 1) { ?>
        <?php if ($i == $count || $i % $column == 0 || ($row > 1 && $i % $row == 0)): ?>
        </ul>
        </div>
         <?php endif ?>
            <?php } ?>
        <?php if ($carousel == 1 && $row > 1 && $i == $count): ?>
            </div>
        <?php endif ?>
    <?php endforeach ?>
    <?php if($carousel == 0) { ?>
        </ul>
        </div>
    <?php } ?>
<?php endif ?>