<?php
/**
 * @category    DGT
 * @package     DGT_Widget
 * Copyright (C) 2014-2015 dragontheme.com. All Rights Reserved.
 * @license     GNU General Public License version 2 or later
 * @author      dragontheme.com
 * @email       support@dragontheme.com
 */
?>
<?php
/* @var $this DGT_Widget_Block_Widget_Collection */
$productCollection = $this->getData('collection');
$count = $productCollection ? $productCollection->count() : 0;
$carousel = $this->getData('carousel');
$row = $this->getData('row');
$column = $carousel == 1 && $row == 1 ? $count : ($carousel == 1 && $row > 1 ? $row : $this->getData('column'));
/* @var $helper Mage_Catalog_Helper_Image */
$helper = Mage::helper('catalog/image');
$theme = $this->helper('dgtyaris');
$checkbox = $theme->getCfg('product_page/related_products_checkbox');
$class_price = rand(23841, 923324);
?>
<?php if (!$count): ?>
    <p class="note-msg">
        <?php echo $this->__('There are no products matching the selection.') ?>
    </p>
<?php else: ?>
    <?php $i = 0;
    foreach ($productCollection as $_product): ?>
        <?php /* @var $_product Mage_Catalog_Model_Product */ ?>
        <?php if ($carousel == 1 && $row > 1 && $i == 0): ?>
            <div class="owl-carousel">
        <?php endif ?>
        <?php if ($i % $column == 0 || ($row > 1 && $i % $row == 0)): ?>
        <ul class="products-grid <?php echo $carousel && $row == 1 ? ' owl-carousel' : '' ?>">
    <?php endif ?>
        <?php $i++ ?>
        <li class="item product-item">
            <div class="item-inner">
                <div class="product-content products-list">
                    <div class="product-hover">
                        <a class="product-image" href="<?php echo $_product->getProductUrl() ?>"
                           title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>">
                            <?php echo $this->helper('dgtyaris')->getLabel($_product); ?>
                            <span class="front margin-image">
                            <?php if ($carousel == 1): ?>
                                <img class="lazyOwl"
                                     data-srcX2="<?php echo $helper->init($_product, 'small_image')->resize(270 * 2, 340 * 2) ?>"
                                     data-src="<?php echo $helper->init($_product, 'small_image')->resize(270, 340) ?>"
                                     width="270" height="340"
                                     alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"/>
                            <?php else: ?>
                                <img src="<?php echo $helper->init($_product, 'small_image')->resize(270, 340) ?>"
                                     width="270" height="340"
                                     alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"/>
                            <?php endif ?>
                            </span>
                        </a>
                    </div>
                </div>
                <div class="top-actions-inner">
                    <h3 class="product-name">
                        <a href="<?php echo $_product->getProductUrl() ?>"
                           title="<?php echo $this->stripTags($_product->getName(), null, true) ?>">
                            <?php echo $this->escapeHtml($_product->getName()) ?>
                        </a>
                    </h3>
                    <?php echo $this->getPriceHtml($_product, true, $class_price); ?>
                    <?php if($checkbox) : ?>
                    <input type="checkbox" class="checkbox related-checkbox pull-left"
                           id="related-checkbox<?php echo $_product->getId() ?>" name="related_products[]"
                           value="<?php echo $_product->getId() ?>"/>
                    <?php endif; ?>
                    <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                </div>
                <div class="dgt-actions clearfix">
                    <div class="addtocart pull-left">
                        <?php if ($_product->isSaleable()): ?>
                            <?php if (!($_product->getTypeInstance(true)->hasRequiredOptions($_product) || $_product->isGrouped()) || $oType == true) { ?>
                                <button type="button" title="<?php echo $this->__('Add To Cart') ?>"
                                        data-placement="top"
                                        class="button btn-cart dgt-tooltip <?php if ($oType == true) echo 'option-file'; ?>"
                                        onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')">
                                        <span>
                                             <span><i
                                                     class="fa fa-shopping-cart"></i><?php echo $this->__('Add To Cart') ?></span>
                                        </span>
                                </button>
                            <?php } else { ?>
                                <?php if (Mage::getStoreConfig('ajaxcart/ajaxcart_config/enable_ajaxcart')) : ?>
                                    <a style="display: none;"
                                       href='<?php echo $this->getUrl('ajaxcart/index/options', array('product_id' => $_product->getId())); ?>'
                                       class='options-cart'
                                       data-id='options-cart-<?php echo $_product->getId() ?>'><?php echo $this->__('Option cart') ?></a>
                                <?php endif; ?>

                                <button type="button" title="<?php echo $this->__('Add To Cart') ?>"
                                        data-placement="top" class="button btn-cart show-options dgt-tooltip"
                                        data-id="<?php echo $_product->getId(); ?>"
                                    <?php if (!Mage::getStoreConfig('ajaxcart/ajaxcart_config/enable_ajaxcart')) { ?>
                                        onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"
                                    <?php } ?> data-submit='<?php echo $this->getAddToCartUrl($_product) ?>'>
                                    <span>
                                       <span><i
                                               class="fa fa-shopping-cart"></i><?php echo $this->__('Add To Cart') ?></span>
                                    </span>
                                </button>

                            <?php } ?>
                        <?php else: ?>
                            <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span>
                            </p>
                        <?php endif; ?>
                    </div>
                    <ul class="add-to-links pull-left">
                        <?php if ($this->helper('wishlist')->isAllow()) : ?>
                            <li class="wishlist">
                                <a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>"
                                   title="<?php echo $this->__('Add To Wishlist') ?>" class="link-wishlist dgt-tooltip"><i
                                        class="fa fa fa-heart-o"></i><?php //echo $this->__('Wishlist') ?></a>
                            </li>
                        <?php endif; ?>
                        <?php if ($_compareUrl = $this->getAddToCompareUrl($_product)): ?>
                            <li class="compare">
                                <a href="<?php echo $_compareUrl ?>" title="<?php echo $this->__('Add To Compare') ?>"
                                   class="link-compare dgt-tooltip"><i
                                        class="fa fa-compress"></i><?php //echo $this->__('Compare') ?></a>
                            </li>
                        <?php endif; ?>
                    </ul>

                </div>
            </div>
        </li>
        <?php if ($i == $count || $i % $column == 0 || ($row > 1 && $i % $row == 0)): ?>
        </ul>
    <?php endif ?>
        <?php if ($carousel == 1 && $row > 1 && $i == $count): ?>
            </div>
        <?php endif ?>
    <?php endforeach ?>
<?php endif ?>

