<?php
/**
 *
 * ------------------------------------------------------------------------------
 * @category     Mono
 * @package DGT Framework
 * ------------------------------------------------------------------------------
 * @copyright    Copyright (C) 2014-2015 dragontheme.com. All Rights Reserved.
 * @license      GNU General Public License version 2 or later;
 * @author       dragontheme.com
 * @email        support@dragontheme.com
 * ------------------------------------------------------------------------------
 *
 */
?>
<!-- navigation BOF -->
<div class="block block-nav">
    <div class="block-title">
        <strong><span><?php echo $this->__('Categories'); ?></span></strong>
    </div>
    <div class="block-content">
        <ul id="categories_nav" class="nav-accordion nav-categories">
            <?php echo $this->renderCategoriesMenuHtml(TRUE, TRUE, 0, 'level-top'); ?>
        </ul>
        <script type="text/javascript">
            $dgt(document).ready(function() {
                $dgt("#categories_nav").dgtAccordionMenu({
                    accordion:true,
                    speed: 400,
                    closedSign: 'collapse',
                    openedSign: 'expand',
                    mouseType: 0,
                    easing: 'easeInOutQuad'
                });
				$dgt(".expand").empty();
            });
        </script>
    </div>
</div>
<!-- navigation EOF -->