<?php
/**
 *
 * ------------------------------------------------------------------------------
 * @category     Mono
 * @package DGT Framework
 * ------------------------------------------------------------------------------
 * @copyright    Copyright (C) 2014-2015 dragontheme.com. All Rights Reserved.
 * @license      GNU General Public License version 2 or later;
 * @author       dragontheme.com
 * @email        support@dragontheme.com
 * ------------------------------------------------------------------------------
 *
 */
?>
<div id="content" class="doc-content"><h2>Introduction</h2>
    <p>Thank you for using our theme. The first word we would like to send our warmest greetings.</p>
    <p><strong>Yaris</strong> is the magento theme, we have spent a long time to researching and developing it with the best features for a shop, it is our heart wants to send you, with good features give the best and easiest way to use, it will help you manage and change your best store</p>
    <p><strong>Demo: </strong><a href="http://dragontheme.com/demo/yaris/">http://dragontheme.com/demo/yaris/</a></p>
    <p><strong>Support: </strong><a href="http://support.dragontheme.com/upload/">http://support.dragontheme.com/upload/</a></p>
    <p><strong>Mail: </strong><a href="mailto:support@dragontheme.com" target="_top">support@dragontheme.com</a></p>
    <h2>Feedback</h2>
    <hr>
    <p>We would happily welcome feedback from you on how, if anywhere, you would like this documentation improved.
        If you would find anything a little bit easier and more helpful that further discuss on the matter. If we
        went into more detail, or explained
        something a little better - We're greatly appreciate your opinions. If you have any problem, please don't
        hesitate to contact us <a href="http://support.dragontheme.com/upload/">http://support.dragontheme.com/upload/</a>.
        All your feedback and comments are appreciated.
    </p>
    <h2>Help &amp; Support</h2>
    <hr>
    <h3> - References</h3>
    <hr>
    <p>You may find these sites useful while installing and configuring your Magento store:</p>
    <h4>   + Magento installation</h4>
    <hr>
    <ul>
        <li>Magento FAQ: <a href="http://www.magentocommerce.com/product/faq">http://www.magentocommerce.com/product/faq</a></li>
        <li>System Requirements: <a href="http://www.magentocommerce.com/system-requirements/">http://www.magentocommerce.com/system-requirements/</a></li>
        <li>Server Compatibility Check: <a href="http://www.magentocommerce.com/knowledge-base/entry/how-do-i-know-if-my-server-is-compatible-with-magento">http://www.magentocommerce.com/knowledge-base/entry/how-do-i-know-if-my-server-is-compatible-with-magento</a></li>
        <li>Installation Guide: <a href="http://www.magentocommerce.com/knowledge-base/entry/magento-installation-guide">http://www.magentocommerce.com/knowledge-base/entry/magento-installation-guide</a></li>
    </ul>
    <h4>   + Magento help</h4>
    <hr>
    <p><strong>Online Magento guide</strong></p>
    <ul>
        <li><p>Table of contents: <a href="http://www.magentocommerce.com/wiki/4_-_themes_and_template_customization/catalog/welcome_to_the_magento_user_s_guide">see the list of all topics</a></p>
        </li>
        <li><p>Selected topics: </p>
            <ol>
                <li><a href="http://www.magentocommerce.com/wiki/welcome_to_the_magento_user_s_guide/chapter_3">Categories, products and attributes</a> </li>
                <li><a href="http://www.magentocommerce.com/wiki/welcome_to_the_magento_user_s_guide/chapter_6">Customers</a> </li>
                <li><a href="http://www.magentocommerce.com/wiki/welcome_to_the_magento_user_s_guide/chapter_4">Payment, shipping and taxes</a> </li>
                <li><a href="http://www.magentocommerce.com/wiki/welcome_to_the_magento_user_s_guide/chapter_5">Promotions and marketing</a></li>
                <li><a href="http://go.magento.com/support/kb">Magento Go Knowledge Base</a></li>
            </ol>
        </li>
    </ul>
    <blockquote>
        <p>Magento Go differs from Magento Community Edition but most of the functionality is the same so this knowledge base might be very useful.</p>
    </blockquote>
    <ul>
        <li>Video Tutorials – Magento Go <a href="http://go.magento.com/video-tutorials">http://go.magento.com/video-tutorials</a></li>
        <li>Magento Wiki  <a href="http://www.magentocommerce.com/wiki/">http://www.magentocommerce.com/wiki/</a></li>
        <li>Magento Forum <a href="http://www.magentocommerce.com/boards/">http://www.magentocommerce.com/boards/</a></li>
        <li>stackoverflow.com <a href="http://stackoverflow.com/questions/tagged/magento">http://stackoverflow.com/questions/tagged/magento</a></li>
        <li>Magento Answers Stack Exchange <a href="http://magento.stackexchange.com/">http://magento.stackexchange.com/</a></li>
    </ul>
    <p>There are many tutorials, acticles and forums to help you learn how to use this Magento theme and its features.
        This section provides helpful links to instructions on commonly used this Magento template features, but you can learn even more by exploring these resources:</p>
</div>