<?php
/**
 * @category    DGT
 * @package     DGT_Widget
 * Copyright (C) 2014-2015 dragontheme.com. All Rights Reserved.
 * @license     GNU General Public License version 2 or later
 * @author      dragontheme.com
 * @email       support@dragontheme.com
 */
?>
<?php
/* @var $this DGT_Widget_Block_Widget */
$_id                = 'dgt-widget-'. rand(123456, 7891011);
$_title             = $this->getConfig('widget_title');
$t                  = microtime();
?>
<div class="dgt-widget product-mini-wrap <?php echo $this->getConfig('classes'); ?> dgt-widget-class"
     id="<?php echo $id ?>"


     data-carousel='<?php echo $this->getConfig('carousel') ?>'
     data-carouselConfig="null"
     data-spinnerImg='<?php echo $this->getSkinUrl('images/ajax-loader.gif') ?>'
     data-countdown='<?php echo $this->getConfig('countdown') ?>'

     data-countdownTemplate="true"
     >
    <?php if ($_title): ?>
        <div class="main-heading">
            <div class="heading-wrapper-title">
                <h3><span><?php echo $_title ?></span></h3>
            </div>
        </div>
    <?php endif ?>
    <?php echo $this->renderCollection('collection', $this->getData('mode'), 'dgt/widget/content-product-mini.phtml') ?>
</div>
<?php //Mage::log(microtime() - $t) ?>
