<?php
/**
 * @category    DGT
 * @package     DGT_Widget
 * Copyright (C) 2014-2015 dragontheme.com. All Rights Reserved.
 * @license     GNU General Public License version 2 or later
 * @author      dragontheme.com
 * @email       support@dragontheme.com
 */
?>
<?php
/* @var $this DGT_Widget_Block_Widget */
$_id                = $this->getConfig('id');
$_title             = $this->getConfig('widget_title');
$_carousel          = $this->getConfig('carousel');
$t                  = microtime();
$_class = ($_carousel) ? 'has-carousel' : 'no-carousel';
?>
<div class="dgt-widget <?php echo $_class . ' ' . $this->getConfig('classes'); ?>" id="<?php echo $_id ?>">
    <?php if ($_title): ?>
    <div class="main-heading">
        <div class="heading-wrapper-title">
            <h3><span><?php echo $_title ?></span></h3>
        </div>
    </div>
    <?php endif ?>
    <?php echo $this->renderCollection('collection', $this->getData('mode'), 'dgt/widget/content-product-default.phtml') ?>
</div>


<script type="text/javascript">
    jQuery('#<?php echo $id; ?> .owl-carousel').owlCarousel(<?php echo $this->getConfig('carousel') ?>);
</script>
<?php //Mage::log(microtime() - $t) ?>
