<?php
/**
 * @category    DGT
 * @package     DGT_Widget
 * Copyright (C) 2014-2015 dragontheme.com. All Rights Reserved.
 * @license     GNU General Public License version 2 or later
 * @author      dragontheme.com
 * @email       support@dragontheme.com
 */
?>
<?php
/* @var $this DGT_Widget_Block_Widget */
$_id                = 'dgt-widget-'. rand(123456, 7891011);
$_title             = $this->getConfig('widget_title');
$t                  = microtime();
?>
<div class="dgt-widget <?php echo $this->getConfig('classes'); ?> rit-widget-class"
     id="<?php echo $id ?>"
     data-animation="<?php echo $this->getConfig('animation'); ?>"
     data-parallax="<?php echo $this->getConfig('parallax') ?>"
     data-carousel="<?php echo $this->getConfig('carousel') ?>"
     data-carouselConfig="null"
     data-countdown="<?php echo $this->getConfig('countdown') ?>"
     data-countdownConfig="null"
     data-countdownTemplate="true"
     data-kenburns="<?php echo $this->getConfig('kenburns') ?>">
    <?php if ($_title): ?>
        <div class="main-heading">
            <div class="heading-wrapper-title">
                <h3><span><?php echo $_title ?></span></h3>
            </div>
        </div>
    <?php endif ?>
    <?php echo $this->renderCollection('collection', $this->getData('mode'), 'dgt/widget/content-product-small.phtml') ?>
</div>
<?php //Mage::log(microtime() - $t) ?>
