<?php
/**
 * @category    DGT
 * @package     DGT_Widget
 * Copyright (C) 2014-2015 dragontheme.com. All Rights Reserved.
 * @license     GNU General Public License version 2 or later
 * @author      dragontheme.com
 * @email       support@dragontheme.com
 */
?>
<?php
/* @var $this DGT_Widget_Block_Widget */
$_id                = 'dgt-widget-'. rand(123456, 7891011);
$_title             = $this->getConfig('widget_title');
$t                  = microtime();
?>
<div class="dgt-widget <?php echo $this->getConfig('classes') ?> dgt-widget-class"
     id="<?php echo $id ?>"


     data-carousel='<?php echo $this->getConfig('carousel') ?>'
     data-carouselConfig="null"
     data-spinnerImg='<?php echo $this->getSkinUrl('images/ajax-loader.gif') ?>'
     data-countdown='<?php echo $this->getConfig('countdown') ?>'

     >
    <?php if ($_title): ?>
        <h2><?php echo $_title ?></h2>
    <?php endif ?>
    <div class="upsell-products-wrap product-boxed">
        <?php echo $this->renderCollection('collection', $this->getData('mode'), 'dgt/widget/content-product-upsell.phtml') ?>
    </div>
</div>
<?php //Mage::log(microtime() - $t) ?>
