<?php
/**
 * @category    DGT
 * @package     DGT_Widget
 * Copyright (C) 2014-2015 dragontheme.com. All Rights Reserved.
 * @license     GNU General Public License version 2 or later
 * @author      dragontheme.com
 * @email       support@dragontheme.com
 */
?>
<?php
$theme = $this->helper('dgtyaris');
$helpImg = $this->helper('dgtyaris/image');
$imgWidth = $theme->getCfg('category/image_width') ? $theme->getCfg('category/image_width') : 295;
$imgHeight = $theme->getCfg('category/image_height') ? $theme->getCfg('category/image_height') : 295;
if ($theme->getCfg('category/aspect_ratio')) {
    $imgHeight = 0;
}
$cfaltimage = $theme->getCfg('category/alt_image');
$hoveraltClass = ($cfaltimage == 1) ? 'front-img' : '';
$_helper = $this->helper('catalog/output');
/* @var $this DGT_Widget_Block_Widget_Collection */
$_productCollection = $this->getData('collection');
$count = $_productCollection ? $_productCollection->count() : 0;
$countdown = $this->getData('countdown');
$carousel = $this->getData('carousel');
$row = $this->getData('row');
$column_no = $this->getData('columnslider');
$class_no = 12 / $column_no;
$column = $carousel == 1 && $row == 1 ? $count : ($carousel == 1 && $row > 1 ? $row : $this->getData('column'));
if($carousel == 0){
    $column = $column_no;
}
$class_price = rand(23841, 923324);
/* @var $helper Mage_Catalog_Helper_Image */
$helper = Mage::helper('catalog/image');
?>

<?php if (!$count): ?>
    <p class="note-msg">
        <?php echo $this->__('There are no products matching the selection.') ?>
    </p>
<?php else: ?>
    <?php $i = 0;
    foreach ($_productCollection as $_product): ?>
        <?php if ($carousel == 1 && $row > 1 && $i == 0): ?>
            <div class="owl-carousel">
        <?php endif ?>
        <?php if ($i % $column == 0 || ($row > 1 && $i % $row == 0)): ?>
        <div class="category-products product-boxed">
        <ul class="products-grid <?php echo $carousel && $row == 1 ? ' owl-carousel' : '' ?>">
    <?php endif ?>
        <?php $i++ ?>
        <li class="item product-mini product-item <?php echo ($carousel == 0) ? 'col-md-' . $class_no . ' ' . 'col-sm-' . $class_no . ' product-no-slider    ' : ''; ?>">
            <div class="item-inner">
                <div class="row">
                    <div class="col-lg-3 col-md-3 col-sm-4 dgt-pr0">
                        <div class="product-content products-list">
                            <div class="product-hover">
                                <a href="<?php echo $_product->getProductUrl() ?>"
                                   title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"
                                   class="product-image">
                                    <span class="front margin-image">
                                    <?php if ($carousel == 1): ?>
                                        <img class="lazyOwl"
                                             data-srcX2="<?php echo $helper->init($_product, 'small_image')->resize($imgWidth * 2, $imgHeight * 2) ?>"
                                             data-src="<?php echo $helper->init($_product, 'small_image')->resize($imgWidth, $imgHeight) ?>"
                                             src="<?php echo $this->getSkinUrl('images/loader.gif') ?>"
                                             width="<?php echo $imgWidth; ?>" height="<?php echo $imgHeight; ?>"
                                             alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"/>
                                    <?php else: ?>
                                        <img src="<?php echo $helper->init($_product, 'small_image')->resize($imgWidth, $imgHeight) ?>"
                                             width="<?php echo $imgWidth; ?>" height="<?php echo $imgHeight; ?>"
                                             alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"/>
                                    <?php endif ?>
                                    </span>
                                    <?php if ($theme->getCfg('category/alt_image')): ?>
                                        <span class="product-img-additional back margin-image">
                                                 <?php echo $theme->getAltImgHtml($_product, $imgWidth, $imgHeight); ?>
                                            </span>
                                    <?php endif; ?>
                                </a>
                            </div>
                            <div class="dgt-actions clearfix">
                                <ul class="add-to-links pull-left">
                                    <li class="main-quickview hidden-xs">
                                        <a href="#" class="button link-quickview btn-quickview dgt-tooltip show-quickview" data-id="<?php echo $_product->getId(); ?>"><i class="fa fa-search"></i></a>
                                    </li>
                                    <a class="product-quickview"
                                       href="<?php echo $this->getUrl('ajaxcart/index/options/product_id/' . $_product->getId()); ?>"
                                       data-id='quickview-<?php echo $_product->getId() ?>'
                                       style='display:none'><?php echo $this->__('Quick view') ?></a>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-9 col-md-9 col-sm-8">
                        <div class="top-actions-inner dgt-mt0 clearfix">
                            <h3 class="product-name dgt-mt0">
                                <a href="<?php echo $_product->getProductUrl() ?>"
                                   title="<?php echo $this->stripTags($_product->getName(), null, true) ?>">
                                    <?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                                </a>
                            </h3>
                            <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                            <?php echo $this->getPriceHtml($_product, true) ?>
                        </div>
                    </div>
                </div>
            </div>
            <div class="product-date" data-date="<?php echo Mage::helper('dgtwidget')->getDate($_product) ?>"></div>
        </li>
        <?php if ($i == $count || $i % $column == 0 || ($row > 1 && $i % $row == 0)): ?>
        </ul>
        </div>
    <?php endif ?>
        <?php if ($carousel == 1 && $row > 1 && $i == $count): ?>
            </div>
        <?php endif ?>
    <?php endforeach ?>
<?php endif ?>