<?php
/**
 * @category    DGT
 * @package     DGT_Widget
 * Copyright (C) 2014-2015 dragontheme.com. All Rights Reserved.
 * @license     GNU General Public License version 2 or later
 * @author      dragontheme.com
 * @email       support@dragontheme.com
 */
?>
<?php
/* @var $this DGT_Widget_Block_Widget */
$_id                = $this->getConfig('id');
$_title             = $this->getConfig('widget_title');
?>
<div class="dgt-widget <?php echo $this->getConfig('classes') ?>" id="<?php echo $_id ?>">
    <?php if ($_title): ?>
        <h2><?php echo $_title ?></h2>
    <?php endif ?>
    <div class="upsell-products-wrap product-boxed">
        <?php echo $this->renderCollection('collection', $this->getData('mode'), 'dgt/widget/content-product-upsell.phtml') ?>
    </div>
</div>

<script type="text/javascript">
    new DGT.Widget('<?php echo $_id ?>', {
        carousel: <?php echo $this->getConfig('carousel') ?>,
        carouselConfig: null,
        countdown: <?php echo $this->getConfig('countdown') ?>,
        countdownConfig: null
    });
</script>
<?php //Mage::log(microtime() - $t) ?>
