<?php
$enable = Mage::getStoreConfig('ajaxcart/ajaxcart_config/enable_ajaxcart');
$_cartQty = $this->getSummaryCount();
?>
<span class="dgt-cart-loading">Loading...</span>
<div class="dgt-cart">
    <div class="dgt-icon-cart">
        <span class="dgt-icon">
            <i class="fa fa-cart-plus"></i>
            <span class="quantity"><?php echo ($_cartQty == '' || $_cartQty == 0) ? '0' : $_cartQty ?></span>
        </span>
        <span class="dgt-total dgt-compare-total">
            <?php echo Mage::helper('checkout')->formatPrice($this->getSubtotal()); ?>
        </span>
    </div>
    <div class="ajaxcart dgt-ajax-container">
        <?php
        $_items = $this->getRecentItems($_cartQty);
        if (count($_items)):
        ?>
            <p class="no-items-in-cart"><?php echo $this->__('You have '. count($_items) .' items in your shopping cart.') ?></p>
            <ul class="clearfix">
                <?php foreach ($_items as $_item): ?>
                    <?php echo $this->getItemHtml($_item) ?>
                <?php endforeach; ?>
            </ul>
            <p class="subtotal">
                <?php if ($this->canApplyMsrp()): ?>
                    <span
                        class="map-cart-sidebar-total"><?php echo $this->__('ORDER TOTAL WILL BE DISPLAYED BEFORE YOU SUBMIT THE ORDER'); ?></span>
                <?php else: ?>
                    <span><?php echo $this->__('Total:') ?></span> <?php echo Mage::helper('checkout')->formatPrice($this->getSubtotal()) ?>
                    <?php if ($_subtotalInclTax = $this->getSubtotalInclTax()): ?>
                        <br/>(<?php echo Mage::helper('checkout')->formatPrice($_subtotalInclTax) ?> <?php echo Mage::helper('tax')->getIncExcText(true) ?>)
                    <?php endif; ?>
                <?php endif; ?>
            </p>
            <div class="dgt-ajax-checkout">
                <a href="<?php echo $this->getUrl('checkout/cart') ?>" class="view-cart">
                    <span><?php echo $this->__('View cart') ?></span>
                </a>
                <?php if (Mage::getStoreConfig('opc/global/status')) { ?>
                    <a href="<?php echo $this->getUrl('onepage') ?>"><span><?php echo $this->__('Checkout') ?></span></a>
                <?php } else { ?>
                    <a href="<?php echo $this->getCheckoutUrl() ?>"><span><?php echo $this->__('Checkout') ?></span></a>
                <?php }?>
            </div>
        <?php else: ?>
            <p class="no-items-in-cart"><?php echo $this->__('You have no items in your shopping cart.') ?></p>
        <?php endif; ?>
    </div>
</div>
<script type="text/javascript">
    var datatext = {};
    datatext.load = '<i class="fa fa-spinner fa-spin"></i>';
</script>