<?php
/**
 *
 * ------------------------------------------------------------------------------
 * @category     Mono
 * @package DGT Framework
 * ------------------------------------------------------------------------------
 * @copyright    Copyright (C) 2014-2015 dragontheme.com. All Rights Reserved.
 * @license      GNU General Public License version 2 or later;
 * @author       dragontheme.com
 * @email        support@dragontheme.com
 * ------------------------------------------------------------------------------
 *
 */
?>
<!-- navigation BOF -->
<?php 
$megaeffect = Mage::getStoreConfig('dgtyaris/menu/menuleft_effect');
$_menu = $this->renderCategoriesMenuHtml(FALSE, FALSE, 0, 'level-top', 'sub-wrapper' );
$routeName = Mage::app()->getRequest()->getRouteName();
$identifier = Mage::getSingleton('cms/page')->getIdentifier();
 
?>
<?php if($_menu): ?>
<div class="dgt-menu-vertical-wrap block hidden-xs <?php echo 'effect-' . $megaeffect; ?>">
    <div class="block-title">
        <strong>
             <span class="fa fa-compress"></span>
            <span><?php echo $this->__('Categories'); ?></span>
        </strong>
    </div>
	<div class="dgt-menu-vertical">
		<ul class="dgt-vertical-mega">
			<!--<?php if(Mage::getStoreConfig('dgtyaris/menu/home')){?>
			<li class="level0 home level-top<?php if($routeName == 'cms' && $identifier == 'home') {echo " active";}?> dgt-dropdown parent">
				<a href="<?php echo $this->getBaseUrl(); ?>" class="level-top"><span><?php echo $this->__('Home'); ?></span></a>
			</li> 
			<?php }?>-->
			<?php
			echo $_menu;
			?>
		</ul>
	</div>
</div>
<script type="text/javascript">
    $dgt(function(){
        $dgt(".dgt-vertical-mega").vmegamenu({
            'animation':'<?php echo $megaeffect;?>',
            'direction': 'vertical',
            'mm_timeout': 50
	    });
    });
</script>
<?php endif ?>
<!-- navigation EOF -->