<?php 
$isResponsive = Mage::helper('dgtyaris')->getThemeLayoutCfg('responsive/responsive');
?>
<script type="text/javascript">
    var dgtThemes = {};
    dgtThemes.responsive = <?php echo ($isResponsive ? 'true' : 'false'); ?>;
    <?php if($isResponsive):?>
    dgtThemes.maxBreak = 1170;
    <?php else:?>
    dgtThemes.maxBreak = 970;
    <?php endif;?>
	dgtThemes.url = '<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>';
</script>