<?php
/**
 * @category    DGT
 * @package     DGT_Widget
 * Copyright (C) 2014-2015 dragontheme.com. All Rights Reserved.
 * @license     GNU General Public License version 2 or later
 * @author      dragontheme.com
 * @email       support@dragontheme.com
 */
?>
<?php
$blocks     = $this->getBlocks();
$id         = $this->getConfig('id');
$scroll     = $this->getConfig('scroll');
$title      = $this->getConfig('widget_title');
?>
<div class="<?php echo $this->getConfig('classes') ?>" id="<?php echo $id ?>">
    <?php if ($title): ?>
        <h2><?php echo $title ?></h2>
    <?php endif ?>
    <div class="<?php echo $scroll==1 ? 'owl-carousel ' : '' ?>">
        <?php foreach ($blocks as $block): ?>
            <div class="<?php echo $block['class']?>">
                <?php echo $block['content'] ?>
            </div>
        <?php endforeach ?>
    </div>

    <script type="text/javascript">
        document.observe("dom:loaded", function() {
            new DGT.Widget('<?php echo $id ?>', {
                animation: <?php echo $this->getConfig('animation') ?>,
                parallax: <?php echo $this->getConfig('parallax') ?>,
                carousel: <?php echo $this->getConfig('carousel') ?>,
                carouselConfig: null,
                kenburns: <?php echo $this->getConfig('kenburns') ?>
            });
        });
    </script>
</div>
