<?php
/**
 * @category    DGT
 * @package     DGT_Widget
 * Copyright (C) 2014-2015 dragontheme.com. All Rights Reserved.
 * @license     GNU General Public License version 2 or later
 * @author      dragontheme.com
 * @email       support@dragontheme.com
 */
?>
<?php
$blocks     = $this->getBlocks();
$id         = $this->getConfig('id');
$scroll     = $this->getConfig('scroll');
$title      = $this->getConfig('widget_title');
?>
<div class="<?php echo $this->getConfig('classes') ?> dgt-widget-class"
     id="<?php echo $id ?>"


     data-carousel='<?php echo $this->getConfig('carousel') ?>'
     data-carouselConfig="null"
     >
    <?php if ($title): ?>
        <h2><?php echo $title ?></h2>
    <?php endif ?>
    <div class="<?php echo $scroll==1 ? 'owl-carousel ' : '' ?>">
        <?php foreach ($blocks as $block): ?>
            <div class="<?php echo $block['class']?>">
                <?php echo $block['content'] ?>
            </div>
        <?php endforeach ?>
    </div>
</div>
