<?php
/**
 * @category    DGT
 * @package     DGT_Widget
 * Copyright (C) 2014-2015 dragontheme.com. All Rights Reserved.
 * @license     GNU General Public License version 2 or later
 * @author      dragontheme.com
 * @email       support@dragontheme.com
 */
?>
<?php
/* @var $this DGT_Widget_Block_Widget */
$_id                = $this->getConfig('id');
$_title             = $this->getConfig('widget_title');
$t                  = microtime();
?>
<div class="<?php echo $this->getConfig('classes') ?> dgt-widget-class"
     id="<?php echo $id ?>"


     data-carousel='<?php echo $this->getConfig('carousel') ?>'
     data-carouselConfig="null"
     data-spinnerImg='<?php echo $this->getSkinUrl('images/ajax-loader.gif') ?>'
     data-countdown='<?php echo $this->getConfig('countdown') ?>'

     >
    <?php if ($_title): ?>
        <h2><?php echo $_title ?></h2>
    <?php endif ?>
    <?php echo $this->renderCollection('collection', $this->getData('mode'), 'dgt/widget/collection.phtml') ?>
</div>
<script type="text/javascript" src="<?php echo Mage::getBaseUrl('js') ?>dgt/widget/frontend.js"></script>
<script type="text/javascript">
    new DGT.Widget('<?php echo $_id ?>', {
        animation: <?php echo $this->getConfig('animation') ?>,
        parallax: <?php echo $this->getConfig('parallax') ?>,
        carousel: <?php echo $this->getConfig('carousel') ?>,
        carouselConfig: null,
        countdown: <?php echo $this->getConfig('countdown') ?>,
        countdownConfig: null,
        kenburns: <?php echo $this->getConfig('kenburns') ?>
    });
</script>
<?php //Mage::log(microtime() - $t) ?>
