    <?php
/**
 *
 * ------------------------------------------------------------------------------
 * @category     Mono
 * @package DGT Framework
 * ------------------------------------------------------------------------------
 * @copyright    Copyright (C) 2014-2015 dragontheme.com. All Rights Reserved.
 * @license      GNU General Public License version 2 or later;
 * @author       dragontheme.com
 * @email        support@dragontheme.com
 * ------------------------------------------------------------------------------
 *
 */
?>
<!-- navigation BOF -->
<?php 
$theme = $this->helper('dgtyaris');
$megaeffect = Mage::getStoreConfig('dgtyaris/menu/effect');
$sticky_logo = $theme->getCfg('header/sticky_logo');
$_menu = $this->renderCategoriesMenuHtml(FALSE, FALSE, 0, 'level-top', 'sub-wrapper' );
$routeName = Mage::app()->getRequest()->getRouteName();
$identifier = Mage::getSingleton('cms/page')->getIdentifier(); 
 
?>
<?php if($_menu): ?>
<?php
    $logoSrc = $this->getSkinUrl();
    $logoArc = Mage::getStoreConfig('design/header/logo_alt');
?>

<div class="dgt-main-menu <?php echo 'effect-' . $megaeffect; ?>">
    <ul id="dgt-navigation" class="megamenu">
        <li class="level0 home level-top visible-sm">
            <a href="#" class="dgt-canvas-button dgt-tooltip" data-original-title="Click Show Menu" data-placement="top">
                <span><i class="fa fa-align-justify"></i></span>
            </a>
        </li>
        <?php if(Mage::getStoreConfig('dgtyaris/menu/home')){?>
        <li class="level0 home level-top <?php if($routeName == 'cms' && $identifier == 'home') {echo " active";}?> dgt-dropdown parent">
            <a href="<?php echo $this->getBaseUrl(); ?>" class="level-top"><span><?php echo $this->__('Home'); ?></span></a>
        </li>
        <?php }?>
        <?php
        echo $_menu;
        if(Mage::getStoreConfig('dgtyaris/menu/enable_custom')){
            $getidentifier = Mage::getStoreConfig('dgtyaris/menu/static_identifier');
            $arrayidentifier = explode(";", $getidentifier);
            foreach($arrayidentifier as $mcustom){
                $static_block = explode(':', $mcustom);
                $custom_menu = Mage::getModel('cms/block')->load($static_block[0]);
                if($static_block[1]) $class = 'menu-item-'.$static_block[1];
                if($custom_menu->getIsActive()) {
                    echo '
                    <li class="level0 level-top parent dgt-custom-block '.$class.'">
                        <a href="#" class="level-top">
                            <span>'.$custom_menu->getTitle().'</span>
                        </a>
                        <div class="sub-wrapper">'.$this->getLayout()->createBlock('cms/block')->setBlockId($static_block[0])->toHtml().'</div>
                    </li>';
                }
            }
            $urlkey = Mage::getStoreConfig('dgtyaris/menu/url_key');
            $arrayUrlKey = explode(";", $urlkey);
            foreach($arrayUrlKey as $url){
                $condition = explode(':', $url);
                $page = Mage::getModel('cms/page')->load($condition[0], 'identifier');
                if(isset($condition[1])) $class = 'menu-item-'.$condition[1];
                if($page->getIsActive()) {
            ?>
                <li class="level0 level-top parent dgt-custom-block <?php if($routeName == 'cms' && $identifier == $page->getIdentifier()) {echo " active";}?> <?php echo $class;?>">
                    <a href="<?php echo Mage::helper('cms/page')->getPageUrl($condition[0]);?>" class="level-top">
                        <span><?php echo $page->getTitle();?></span>
                    </a>
                </li>
            <?php
                }
            }
        }
        ?>
    </ul>
</div>
<script type="text/javascript">
    $dgt(function(){
        $dgt(".megamenu").megamenu({
            'animation':'<?php echo $megaeffect;?>',
            'mm_timeout': 150
	    });
    });
</script>
<?php endif ?>
<!-- navigation EOF -->