<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Blog
 * @version    1.3.8
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php $posts = $this->getPosts(); ?>
<div id="messages_product_view">
    <?php Mage::app()->getLayout()->getMessagesBlock()->setMessages(Mage::getSingleton('customer/session')->getMessages(true)); ?>
    <?php echo Mage::app()->getLayout()->getMessagesBlock()->getGroupedHtml(); ?>
</div>

<?php echo $this->getChildHtml('aw_blog_comments_toolbar'); ?>
<div class="blog-wrap row">
    <?php foreach ($posts as $post): ?>
        <div class="blog-item col-sm-4 col-md-4">
            <div class="blog-image dgt-img-hover">
                <a href="<?php echo $post->getAddress(); ?>">
                    <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . $post->getFeaturedImage() ?>" alt="featuredImage"/>
                    <span class="img-hover">
                        <i class="fa fa-plus"></i>
                    </span>
                </a>
            </div>
            <div class="blog-title">
                <h3><a href="<?php echo $post->getAddress(); ?>"><?php echo $post->getTitle(); ?></a></h3>
            </div>
            <div class="postDetails">
                <?php $postCats = $post->getCats(); ?>
                <?php if (!empty($postCats)): ?>
                    <span class="post-in">
                    <i class="fa fa-cloud"></i>
                        <?php foreach ($postCats as $data): ?>
                            <a href="<?php echo $data['url']; ?>"><?php echo $data['title']; ?></a>
                        <?php endforeach; ?>
                    </span>
                <?php else: ?>
                    <?php echo Mage::helper('blog')->__('Posted'); ?>
                <?php endif; ?>
                <span class="blog-user"><i class="fa  fa-user"></i><span><?php echo $post->getUser(); ?></span></span>
            </div>
            <div class="blog-excerpt"><?php echo $post->getPostContent(); ?></div>
        </div>
    <?php endforeach; ?>
</div>
<?php echo $this->getChildHtml('aw_blog_comments_toolbar'); ?>
